version: 1.0.{build}
os: Visual Studio 2015
configuration: Release
init:
- cmd: >-
    git config --global core.autocrlf true

    mkdir ..\..\..\keys\antlr

    "C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.6 Tools\sn.exe" -k ..\..\..\keys\antlr\Key.snk
install:
- git submodule update --init --recursive
build_script:
- cd build\prep
- powershell -Command .\prepare.ps1 -Logger "${env:ProgramFiles}\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
- cd ..\..
test_script:
- vstest.console /logger:Appveyor /TestCaseFilter:"TestCategory!=Visualizer" "C:\projects\antlrcs\Antlr4.Test.StringTemplate\bin\net40\%CONFIGURATION%\Antlr4.Test.StringTemplate.dll"
- vstest.console /logger:Appveyor /TestCaseFilter:"TestCategory!=Visualizer" "C:\projects\antlrcs\Antlr4.Test.StringTemplate\bin\netstandard\%CONFIGURATION%\Antlr4.Test.StringTemplate.dll"
artifacts:
- path: build\prep\nuget\*.nupkg
- path: build\prep\dist\*.7z
